name: Book Plasma Donation Appointment

on:
  workflow_dispatch:
    inputs:
      skip_booking:
        description: 'Skip actual booking submission (true/false)'
        required: false
        default: 'false'
  schedule:
    - cron: '0 20 * * 1,4' # Run at 17:00 UTC on Monday (1) and Thursday (4)

jobs:
  book-appointment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run booking script
        env:
          BLUTSPENDE_SURNAME: ${{ secrets.BLUTSPENDE_SURNAME }}
          BLUTSPENDE_DONOR_ID: ${{ secrets.BLUTSPENDE_DONOR_ID }}
          BLUTSPENDE_EMAIL: ${{ secrets.BLUTSPENDE_EMAIL }}
          GOOGLE_CALENDAR_ID: ${{ secrets.GOOGLE_CALENDAR_ID }}
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
        run: |
          01_donor_automation_with_calendar_appointment_as_github.py ${{ github.event.inputs.skip_booking == 'false' && '--skip-booking' || '' }}
